// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seqtqwpsellspkxhbeky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlcXRxd3BzZWxsc3BreGhiZWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwNDQ1NDQsImV4cCI6MjEwNDYyMDU0NH0.RruVV7JM-QO_Og1TJ_mgv6-rLEfBOncCDpYIiIScoOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});